### PR TITLE
fix: uppercase readme+contirbuting docs

### LINKED ISSUE #76: fully uppercase Readme.md/Contributing.md
this is purely aestethic on my part, but i think it's generally more conventional. we have LICENSE and CHANGELOG, this change would make our "repo doc files" consistent.

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #76 (assuming we have consensus to do so)

### CODE REVIEW

**Comment by Enrico2** [comment]
The lowercase name is mentioned a few times:
```
$ git grep Readme.md
.github/workflows/build.yml:  RELEASE_ADDS: Readme.md
.github/workflows/release.yml:  RELEASE_ADDS: Readme.md
Contributing.md:After you have opened your PR and all of the status checks are passing, please assign it to one of the maintainers (found in the bottom of [the readme](./Readme.md#contributing) who will review it and give feedback.
```

**Comment by ashleygwilliams** [comment]
added and rebased.

**Comment by Enrico2** [comment]
Sorry, there's also some `Contributing.md` references (`git grep Contributing.md`)

**Comment by ashleygwilliams** [comment]
ok *should be good this time*

**Pull request merged**
